on:
  push:
    branches:
      - main
  pull_request:

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check

  fmt:
    name: Rustfmt
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all -- -D warnings

  msrv:
    name: MSRV
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.75.0
      - run: cargo check --lib

  test:
    name: Test Core
    needs: [fmt, clippy, msrv]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --lib

  test-integration:
    name: Test Integration
    needs: [fmt, clippy, msrv]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: RUST_TEST_THREADS=1 cargo test --test '*'

  test-fetcher:
    name: Test Fetcher
    needs: [fmt, clippy, msrv]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: RUST_TEST_THREADS=1 cargo test -p chromiumoxide_fetcher

  check-examples:
    name: Check Examples
    needs: [fmt, clippy, msrv]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check examples with default features
        run: cargo check --examples --features tokio-runtime,bytes
      - name: Check async-std examples
        run: cargo check --examples --features async-std-runtime
      - name: Check fetcher examples
        run: |
          cargo check --example fetcher --features _fetcher-native-tokio
          cargo check --example fetcher-async-std --features async-std-runtime,_fetcher-native-async-std
